repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-toml
    -   id: requirements-txt-fixer
    -   id: mixed-line-ending
        args: [--fix=lf]

-   repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
    -   id: black
        args: [--line-length=100]

-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        args: [--profile=black, --line-length=100]

-   repo: https://github.com/pycqa/pylint
    rev: v3.0.1
    hooks:
    -   id: pylint
        additional_dependencies: [
            "pytest>=7.4.0",
            "fastapi>=0.115.12",
            "uvicorn>=0.34.0",
            "discord-py>=2.5.2",
            "python-dotenv>=1.1.0",
            "openai>=1.70.0",
            "python-telegram-bot>=22.0",
            "redis>=5.0.1",
            "pydantic>=2.6.0",
        ]
        args: [--disable=C0111, --max-line-length=100]
        exclude: ^tests/|^docs/|^examples/
